name: Model Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
        pip install pytest numpy
        
    - name: Test Parameter Count
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/test_model.py::test_parameter_count -v
        
    - name: Test Model Accuracy
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/test_model.py::test_model_accuracy -v